"""фюсртыхэ ЁхщЄшэу яюы№чютрЄхыхщ

Revision ID: 3bab197d486e
Revises: 399bdf616d2b
Create Date: 2020-05-04 20:30:34.843330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bab197d486e'
down_revision = '399bdf616d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rating')
    # ### end Alembic commands ###
