"""изменены отношения для подписок

Revision ID: 6373184fcb70
Revises: 4c2971c096d2
Create Date: 2020-04-30 21:04:02.662413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6373184fcb70'
down_revision = '4c2971c096d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
